name: Scheduled release

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Make a release
        run: |
          git config --global user.email "louis.beaumont@gmail.com"
          git config --global user.name "louis030195"
          VERSION=$(cat VERSION.txt | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo $VERSION > VERSION.txt
          echo "Releasing version $VERSION"
          git add .
          echo "Committing '$VERSION: 🙈 $(date +%Y-%m-%d_%H:%M:%S) 🙈'"
          git commit -m "$VERSION: $COMMIT"
          git push origin main
          git tag $VERSION
          git push origin $VERSION
      -
        name: Set version in env
        run: |
          VERSION=$(cat VERSION.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./google.cloud.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            louis030195/gitpod-google-cloud:latest
            louis030195/gitpod-google-cloud:$VERSION
            ghcr.io/louis030195/gitpod-google-cloud:latest
            ghcr.io/louis030195/gitpod-google-cloud:$VERSION
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: louis030195/gitpod-docker