name: Scheduled release

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Make a release
        run: |
          git config --global user.email "louis.beaumont@gmail.com"
          git config --global user.name "louis030195"
          V=$(cat VERSION.txt | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo $V > VERSION.txt
          echo "Releasing version $VERSION"
          git add .
          echo "Committing '$VERSION: 🙈 $(date +%Y-%m-%d_%H:%M:%S) 🙈'"
          git commit -m "$VERSION: $COMMIT"
          git push origin main
          git tag $VERSION
          git push origin $VERSION
